feat: Expose Joi along with Bagger instance. Fixes #60
digitalroute/bagger pull request #62
Opened 2022-02-14 16:26 UTC by Saeger

Making Bagger exposes JOI by default. #60

2022-02-14 16:53 UTC, Saeger commented
@juliuscc please review

2022-02-15 08:12 UTC, tgun89 requested changes

2022-02-15 08:12 UTC, tgun89 commented on README.md
> +- ✨ **joi compatibility:** Enables developers to use the same schemas for validation and documentation. Embeded Joi is now exposed by default.
```suggestion
- ✨ **joi compatibility:** Enables developers to use the same schemas for validation and documentation. Embedded Joi is now exposed by default.
```

2022-02-15 08:12 UTC, tgun89 commented on README.md
> +const bagger = require('@digitalroute/bagger').bagger;
```suggestion
const { bagger } = require('@digitalroute/bagger');
```

2022-02-15 08:12 UTC, tgun89 commented on lib/bagger.ts
> +export const defaultInstance = new Bagger();
```suggestion
export const bagger = new Bagger();
```

2022-02-15 08:12 UTC, tgun89 commented on lib/index.ts
> +import { defaultInstance as bagger } from './bagger';
```suggestion
import { bagger } from './bagger';
```

2022-02-15 08:12 UTC, tgun89 commented on rollup.config.ts
> +const libraryName = 'index';
```suggestion
const libEntrypoint = 'index';
```

2022-02-15 08:12 UTC, tgun89 commented on rollup.config.ts
>    input: `lib/${libraryName}.ts`,
```suggestion
  input: `lib/${libEntrypoint}.ts`,
```

2022-02-15 08:12 UTC, tgun89 commented on test/configuration.test.ts
>  import joi from 'joi';
import joi from `lib` instead

2022-02-15 09:52 UTC, tgun89 approved these changes
🚀

2022-02-15 09:52 UTC, merged